// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dataTypes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from dataTypes.proto</summary>
public static partial class DataTypesReflection {

  #region Descriptor
  /// <summary>File descriptor for dataTypes.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DataTypesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9kYXRhVHlwZXMucHJvdG8i5QEKC0Jhc2VNZXNzYWdlEhsKA3BvcxgBIAEo",
          "CzIMLlZlY3RvcjJEYXRhSAASGgoQbmV3UGxheWVyUmVxdWVzdBgCIAEoCEgA",
          "EigKDnVwZGF0ZUNoYXJEYXRhGAMgASgLMg4uQ2hhcmFjdGVyRGF0YUgAEigK",
          "Dm5ld1BsYXllckdyYW50GAQgASgLMg4uQ2hhcmFjdGVyRGF0YUgAEicKDW5l",
          "d1JlbW90ZUNoYXIYBSABKAsyDi5DaGFyYWN0ZXJEYXRhSAASGAoOcmVtb3Zl",
          "Q2hhck9mSUQYBiABKAVIAEIGCgRUeXBlIiMKC1ZlY3RvcjJEYXRhEgkKAXgY",
          "ASABKAISCQoBeRgCIAEoAiI/Cg1DaGFyYWN0ZXJEYXRhEhMKC2NoYXJhY3Rl",
          "cklEGAEgASgFEhkKA3BvcxgCIAEoCzIMLlZlY3RvcjJEYXRhYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BaseMessage), global::BaseMessage.Parser, new[]{ "Pos", "NewPlayerRequest", "UpdateCharData", "NewPlayerGrant", "NewRemoteChar", "RemoveCharOfID" }, new[]{ "Type" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Vector2Data), global::Vector2Data.Parser, new[]{ "X", "Y" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CharacterData), global::CharacterData.Parser, new[]{ "CharacterID", "Pos" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class BaseMessage : pb::IMessage<BaseMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BaseMessage> _parser = new pb::MessageParser<BaseMessage>(() => new BaseMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BaseMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataTypesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseMessage(BaseMessage other) : this() {
    switch (other.TypeCase) {
      case TypeOneofCase.Pos:
        Pos = other.Pos.Clone();
        break;
      case TypeOneofCase.NewPlayerRequest:
        NewPlayerRequest = other.NewPlayerRequest;
        break;
      case TypeOneofCase.UpdateCharData:
        UpdateCharData = other.UpdateCharData.Clone();
        break;
      case TypeOneofCase.NewPlayerGrant:
        NewPlayerGrant = other.NewPlayerGrant.Clone();
        break;
      case TypeOneofCase.NewRemoteChar:
        NewRemoteChar = other.NewRemoteChar.Clone();
        break;
      case TypeOneofCase.RemoveCharOfID:
        RemoveCharOfID = other.RemoveCharOfID;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseMessage Clone() {
    return new BaseMessage(this);
  }

  /// <summary>Field number for the "pos" field.</summary>
  public const int PosFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Vector2Data Pos {
    get { return typeCase_ == TypeOneofCase.Pos ? (global::Vector2Data) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Pos;
    }
  }

  /// <summary>Field number for the "newPlayerRequest" field.</summary>
  public const int NewPlayerRequestFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool NewPlayerRequest {
    get { return typeCase_ == TypeOneofCase.NewPlayerRequest ? (bool) type_ : false; }
    set {
      type_ = value;
      typeCase_ = TypeOneofCase.NewPlayerRequest;
    }
  }

  /// <summary>Field number for the "updateCharData" field.</summary>
  public const int UpdateCharDataFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CharacterData UpdateCharData {
    get { return typeCase_ == TypeOneofCase.UpdateCharData ? (global::CharacterData) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.UpdateCharData;
    }
  }

  /// <summary>Field number for the "newPlayerGrant" field.</summary>
  public const int NewPlayerGrantFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CharacterData NewPlayerGrant {
    get { return typeCase_ == TypeOneofCase.NewPlayerGrant ? (global::CharacterData) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.NewPlayerGrant;
    }
  }

  /// <summary>Field number for the "newRemoteChar" field.</summary>
  public const int NewRemoteCharFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CharacterData NewRemoteChar {
    get { return typeCase_ == TypeOneofCase.NewRemoteChar ? (global::CharacterData) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.NewRemoteChar;
    }
  }

  /// <summary>Field number for the "removeCharOfID" field.</summary>
  public const int RemoveCharOfIDFieldNumber = 6;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RemoveCharOfID {
    get { return typeCase_ == TypeOneofCase.RemoveCharOfID ? (int) type_ : 0; }
    set {
      type_ = value;
      typeCase_ = TypeOneofCase.RemoveCharOfID;
    }
  }

  private object type_;
  /// <summary>Enum of possible cases for the "Type" oneof.</summary>
  public enum TypeOneofCase {
    None = 0,
    Pos = 1,
    NewPlayerRequest = 2,
    UpdateCharData = 3,
    NewPlayerGrant = 4,
    NewRemoteChar = 5,
    RemoveCharOfID = 6,
  }
  private TypeOneofCase typeCase_ = TypeOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TypeOneofCase TypeCase {
    get { return typeCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearType() {
    typeCase_ = TypeOneofCase.None;
    type_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BaseMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BaseMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Pos, other.Pos)) return false;
    if (NewPlayerRequest != other.NewPlayerRequest) return false;
    if (!object.Equals(UpdateCharData, other.UpdateCharData)) return false;
    if (!object.Equals(NewPlayerGrant, other.NewPlayerGrant)) return false;
    if (!object.Equals(NewRemoteChar, other.NewRemoteChar)) return false;
    if (RemoveCharOfID != other.RemoveCharOfID) return false;
    if (TypeCase != other.TypeCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (typeCase_ == TypeOneofCase.Pos) hash ^= Pos.GetHashCode();
    if (typeCase_ == TypeOneofCase.NewPlayerRequest) hash ^= NewPlayerRequest.GetHashCode();
    if (typeCase_ == TypeOneofCase.UpdateCharData) hash ^= UpdateCharData.GetHashCode();
    if (typeCase_ == TypeOneofCase.NewPlayerGrant) hash ^= NewPlayerGrant.GetHashCode();
    if (typeCase_ == TypeOneofCase.NewRemoteChar) hash ^= NewRemoteChar.GetHashCode();
    if (typeCase_ == TypeOneofCase.RemoveCharOfID) hash ^= RemoveCharOfID.GetHashCode();
    hash ^= (int) typeCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (typeCase_ == TypeOneofCase.Pos) {
      output.WriteRawTag(10);
      output.WriteMessage(Pos);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerRequest) {
      output.WriteRawTag(16);
      output.WriteBool(NewPlayerRequest);
    }
    if (typeCase_ == TypeOneofCase.UpdateCharData) {
      output.WriteRawTag(26);
      output.WriteMessage(UpdateCharData);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerGrant) {
      output.WriteRawTag(34);
      output.WriteMessage(NewPlayerGrant);
    }
    if (typeCase_ == TypeOneofCase.NewRemoteChar) {
      output.WriteRawTag(42);
      output.WriteMessage(NewRemoteChar);
    }
    if (typeCase_ == TypeOneofCase.RemoveCharOfID) {
      output.WriteRawTag(48);
      output.WriteInt32(RemoveCharOfID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (typeCase_ == TypeOneofCase.Pos) {
      output.WriteRawTag(10);
      output.WriteMessage(Pos);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerRequest) {
      output.WriteRawTag(16);
      output.WriteBool(NewPlayerRequest);
    }
    if (typeCase_ == TypeOneofCase.UpdateCharData) {
      output.WriteRawTag(26);
      output.WriteMessage(UpdateCharData);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerGrant) {
      output.WriteRawTag(34);
      output.WriteMessage(NewPlayerGrant);
    }
    if (typeCase_ == TypeOneofCase.NewRemoteChar) {
      output.WriteRawTag(42);
      output.WriteMessage(NewRemoteChar);
    }
    if (typeCase_ == TypeOneofCase.RemoveCharOfID) {
      output.WriteRawTag(48);
      output.WriteInt32(RemoveCharOfID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (typeCase_ == TypeOneofCase.Pos) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerRequest) {
      size += 1 + 1;
    }
    if (typeCase_ == TypeOneofCase.UpdateCharData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateCharData);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerGrant) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(NewPlayerGrant);
    }
    if (typeCase_ == TypeOneofCase.NewRemoteChar) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(NewRemoteChar);
    }
    if (typeCase_ == TypeOneofCase.RemoveCharOfID) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RemoveCharOfID);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BaseMessage other) {
    if (other == null) {
      return;
    }
    switch (other.TypeCase) {
      case TypeOneofCase.Pos:
        if (Pos == null) {
          Pos = new global::Vector2Data();
        }
        Pos.MergeFrom(other.Pos);
        break;
      case TypeOneofCase.NewPlayerRequest:
        NewPlayerRequest = other.NewPlayerRequest;
        break;
      case TypeOneofCase.UpdateCharData:
        if (UpdateCharData == null) {
          UpdateCharData = new global::CharacterData();
        }
        UpdateCharData.MergeFrom(other.UpdateCharData);
        break;
      case TypeOneofCase.NewPlayerGrant:
        if (NewPlayerGrant == null) {
          NewPlayerGrant = new global::CharacterData();
        }
        NewPlayerGrant.MergeFrom(other.NewPlayerGrant);
        break;
      case TypeOneofCase.NewRemoteChar:
        if (NewRemoteChar == null) {
          NewRemoteChar = new global::CharacterData();
        }
        NewRemoteChar.MergeFrom(other.NewRemoteChar);
        break;
      case TypeOneofCase.RemoveCharOfID:
        RemoveCharOfID = other.RemoveCharOfID;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::Vector2Data subBuilder = new global::Vector2Data();
          if (typeCase_ == TypeOneofCase.Pos) {
            subBuilder.MergeFrom(Pos);
          }
          input.ReadMessage(subBuilder);
          Pos = subBuilder;
          break;
        }
        case 16: {
          NewPlayerRequest = input.ReadBool();
          break;
        }
        case 26: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.UpdateCharData) {
            subBuilder.MergeFrom(UpdateCharData);
          }
          input.ReadMessage(subBuilder);
          UpdateCharData = subBuilder;
          break;
        }
        case 34: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.NewPlayerGrant) {
            subBuilder.MergeFrom(NewPlayerGrant);
          }
          input.ReadMessage(subBuilder);
          NewPlayerGrant = subBuilder;
          break;
        }
        case 42: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.NewRemoteChar) {
            subBuilder.MergeFrom(NewRemoteChar);
          }
          input.ReadMessage(subBuilder);
          NewRemoteChar = subBuilder;
          break;
        }
        case 48: {
          RemoveCharOfID = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::Vector2Data subBuilder = new global::Vector2Data();
          if (typeCase_ == TypeOneofCase.Pos) {
            subBuilder.MergeFrom(Pos);
          }
          input.ReadMessage(subBuilder);
          Pos = subBuilder;
          break;
        }
        case 16: {
          NewPlayerRequest = input.ReadBool();
          break;
        }
        case 26: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.UpdateCharData) {
            subBuilder.MergeFrom(UpdateCharData);
          }
          input.ReadMessage(subBuilder);
          UpdateCharData = subBuilder;
          break;
        }
        case 34: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.NewPlayerGrant) {
            subBuilder.MergeFrom(NewPlayerGrant);
          }
          input.ReadMessage(subBuilder);
          NewPlayerGrant = subBuilder;
          break;
        }
        case 42: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.NewRemoteChar) {
            subBuilder.MergeFrom(NewRemoteChar);
          }
          input.ReadMessage(subBuilder);
          NewRemoteChar = subBuilder;
          break;
        }
        case 48: {
          RemoveCharOfID = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Vector2Data : pb::IMessage<Vector2Data>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Vector2Data> _parser = new pb::MessageParser<Vector2Data>(() => new Vector2Data());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Vector2Data> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataTypesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Vector2Data() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Vector2Data(Vector2Data other) : this() {
    x_ = other.x_;
    y_ = other.y_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Vector2Data Clone() {
    return new Vector2Data(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private float x_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float X {
    get { return x_; }
    set {
      x_ = value;
    }
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private float y_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Y {
    get { return y_; }
    set {
      y_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Vector2Data);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Vector2Data other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
    if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (X != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(X);
    }
    if (Y != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Y);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (X != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(X);
    }
    if (Y != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Y);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (X != 0F) {
      size += 1 + 4;
    }
    if (Y != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Vector2Data other) {
    if (other == null) {
      return;
    }
    if (other.X != 0F) {
      X = other.X;
    }
    if (other.Y != 0F) {
      Y = other.Y;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          X = input.ReadFloat();
          break;
        }
        case 21: {
          Y = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 13: {
          X = input.ReadFloat();
          break;
        }
        case 21: {
          Y = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class CharacterData : pb::IMessage<CharacterData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CharacterData> _parser = new pb::MessageParser<CharacterData>(() => new CharacterData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CharacterData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataTypesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CharacterData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CharacterData(CharacterData other) : this() {
    characterID_ = other.characterID_;
    pos_ = other.pos_ != null ? other.pos_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CharacterData Clone() {
    return new CharacterData(this);
  }

  /// <summary>Field number for the "characterID" field.</summary>
  public const int CharacterIDFieldNumber = 1;
  private int characterID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CharacterID {
    get { return characterID_; }
    set {
      characterID_ = value;
    }
  }

  /// <summary>Field number for the "pos" field.</summary>
  public const int PosFieldNumber = 2;
  private global::Vector2Data pos_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Vector2Data Pos {
    get { return pos_; }
    set {
      pos_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CharacterData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CharacterData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CharacterID != other.CharacterID) return false;
    if (!object.Equals(Pos, other.Pos)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (CharacterID != 0) hash ^= CharacterID.GetHashCode();
    if (pos_ != null) hash ^= Pos.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (CharacterID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(CharacterID);
    }
    if (pos_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Pos);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (CharacterID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(CharacterID);
    }
    if (pos_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Pos);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (CharacterID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CharacterID);
    }
    if (pos_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CharacterData other) {
    if (other == null) {
      return;
    }
    if (other.CharacterID != 0) {
      CharacterID = other.CharacterID;
    }
    if (other.pos_ != null) {
      if (pos_ == null) {
        Pos = new global::Vector2Data();
      }
      Pos.MergeFrom(other.Pos);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          CharacterID = input.ReadInt32();
          break;
        }
        case 18: {
          if (pos_ == null) {
            Pos = new global::Vector2Data();
          }
          input.ReadMessage(Pos);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          CharacterID = input.ReadInt32();
          break;
        }
        case 18: {
          if (pos_ == null) {
            Pos = new global::Vector2Data();
          }
          input.ReadMessage(Pos);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
