// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dataTypes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from dataTypes.proto</summary>
public static partial class DataTypesReflection {

  #region Descriptor
  /// <summary>File descriptor for dataTypes.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DataTypesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9kYXRhVHlwZXMucHJvdG8i9wEKC0Jhc2VNZXNzYWdlEh0KBWlucHV0GAEg",
          "ASgLMgwuUGxheWVySW5wdXRIABIaChBuZXdQbGF5ZXJSZXF1ZXN0GAIgASgJ",
          "SAASKAoOdXBkYXRlQ2hhckRhdGEYAyABKAsyDi5DaGFyYWN0ZXJEYXRhSAAS",
          "KAoObmV3UGxheWVyR3JhbnQYBCABKAsyDi5DaGFyYWN0ZXJEYXRhSAASJwoN",
          "bmV3UmVtb3RlQ2hhchgFIAEoCzIOLkNoYXJhY3RlckRhdGFIABIYCg5yZW1v",
          "dmVDaGFyT2ZJRBgGIAEoBUgAEg4KBG5hbWUYByABKAlIAEIGCgRUeXBlIiMK",
          "C1ZlY3RvcjJEYXRhEgkKAXgYASABKAISCQoBeRgCIAEoAiK1AQoLUGxheWVy",
          "SW5wdXQSHgoDcG9zGAEgASgLMgwuVmVjdG9yMkRhdGFIAYgBARIdCgdsb29r",
          "UG9zGAIgASgLMgwuVmVjdG9yMkRhdGESFAoKUGlja3VwSXRlbRgDIAEoBUgA",
          "EhQKCkl0ZW1BY3Rpb24YBCABKAVIABIXCg1JdGVtQWN0aW9uUG9zGAUgASgI",
          "SAASEgoIRHJvcEl0ZW0YBiABKAhIAEIGCgRJdGVtQgYKBF9wb3MiaAoNQ2hh",
          "cmFjdGVyRGF0YRITCgtjaGFyYWN0ZXJJRBgBIAEoBRIeCgNwb3MYAiABKAsy",
          "DC5WZWN0b3IyRGF0YUgAiAEBEhEKBG5hbWUYAyABKAlIAYgBAUIGCgRfcG9z",
          "QgcKBV9uYW1lYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BaseMessage), global::BaseMessage.Parser, new[]{ "Input", "NewPlayerRequest", "UpdateCharData", "NewPlayerGrant", "NewRemoteChar", "RemoveCharOfID", "Name" }, new[]{ "Type" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Vector2Data), global::Vector2Data.Parser, new[]{ "X", "Y" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInput), global::PlayerInput.Parser, new[]{ "Pos", "LookPos", "PickupItem", "ItemAction", "ItemActionPos", "DropItem" }, new[]{ "Item", "Pos" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CharacterData), global::CharacterData.Parser, new[]{ "CharacterID", "Pos", "Name" }, new[]{ "Pos", "Name" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class BaseMessage : pb::IMessage<BaseMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BaseMessage> _parser = new pb::MessageParser<BaseMessage>(() => new BaseMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BaseMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataTypesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseMessage(BaseMessage other) : this() {
    switch (other.TypeCase) {
      case TypeOneofCase.Input:
        Input = other.Input.Clone();
        break;
      case TypeOneofCase.NewPlayerRequest:
        NewPlayerRequest = other.NewPlayerRequest;
        break;
      case TypeOneofCase.UpdateCharData:
        UpdateCharData = other.UpdateCharData.Clone();
        break;
      case TypeOneofCase.NewPlayerGrant:
        NewPlayerGrant = other.NewPlayerGrant.Clone();
        break;
      case TypeOneofCase.NewRemoteChar:
        NewRemoteChar = other.NewRemoteChar.Clone();
        break;
      case TypeOneofCase.RemoveCharOfID:
        RemoveCharOfID = other.RemoveCharOfID;
        break;
      case TypeOneofCase.Name:
        Name = other.Name;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseMessage Clone() {
    return new BaseMessage(this);
  }

  /// <summary>Field number for the "input" field.</summary>
  public const int InputFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::PlayerInput Input {
    get { return typeCase_ == TypeOneofCase.Input ? (global::PlayerInput) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Input;
    }
  }

  /// <summary>Field number for the "newPlayerRequest" field.</summary>
  public const int NewPlayerRequestFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NewPlayerRequest {
    get { return typeCase_ == TypeOneofCase.NewPlayerRequest ? (string) type_ : ""; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      typeCase_ = TypeOneofCase.NewPlayerRequest;
    }
  }

  /// <summary>Field number for the "updateCharData" field.</summary>
  public const int UpdateCharDataFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CharacterData UpdateCharData {
    get { return typeCase_ == TypeOneofCase.UpdateCharData ? (global::CharacterData) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.UpdateCharData;
    }
  }

  /// <summary>Field number for the "newPlayerGrant" field.</summary>
  public const int NewPlayerGrantFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CharacterData NewPlayerGrant {
    get { return typeCase_ == TypeOneofCase.NewPlayerGrant ? (global::CharacterData) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.NewPlayerGrant;
    }
  }

  /// <summary>Field number for the "newRemoteChar" field.</summary>
  public const int NewRemoteCharFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CharacterData NewRemoteChar {
    get { return typeCase_ == TypeOneofCase.NewRemoteChar ? (global::CharacterData) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.NewRemoteChar;
    }
  }

  /// <summary>Field number for the "removeCharOfID" field.</summary>
  public const int RemoveCharOfIDFieldNumber = 6;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RemoveCharOfID {
    get { return typeCase_ == TypeOneofCase.RemoveCharOfID ? (int) type_ : 0; }
    set {
      type_ = value;
      typeCase_ = TypeOneofCase.RemoveCharOfID;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 7;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return typeCase_ == TypeOneofCase.Name ? (string) type_ : ""; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      typeCase_ = TypeOneofCase.Name;
    }
  }

  private object type_;
  /// <summary>Enum of possible cases for the "Type" oneof.</summary>
  public enum TypeOneofCase {
    None = 0,
    Input = 1,
    NewPlayerRequest = 2,
    UpdateCharData = 3,
    NewPlayerGrant = 4,
    NewRemoteChar = 5,
    RemoveCharOfID = 6,
    Name = 7,
  }
  private TypeOneofCase typeCase_ = TypeOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TypeOneofCase TypeCase {
    get { return typeCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearType() {
    typeCase_ = TypeOneofCase.None;
    type_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BaseMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BaseMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Input, other.Input)) return false;
    if (NewPlayerRequest != other.NewPlayerRequest) return false;
    if (!object.Equals(UpdateCharData, other.UpdateCharData)) return false;
    if (!object.Equals(NewPlayerGrant, other.NewPlayerGrant)) return false;
    if (!object.Equals(NewRemoteChar, other.NewRemoteChar)) return false;
    if (RemoveCharOfID != other.RemoveCharOfID) return false;
    if (Name != other.Name) return false;
    if (TypeCase != other.TypeCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (typeCase_ == TypeOneofCase.Input) hash ^= Input.GetHashCode();
    if (typeCase_ == TypeOneofCase.NewPlayerRequest) hash ^= NewPlayerRequest.GetHashCode();
    if (typeCase_ == TypeOneofCase.UpdateCharData) hash ^= UpdateCharData.GetHashCode();
    if (typeCase_ == TypeOneofCase.NewPlayerGrant) hash ^= NewPlayerGrant.GetHashCode();
    if (typeCase_ == TypeOneofCase.NewRemoteChar) hash ^= NewRemoteChar.GetHashCode();
    if (typeCase_ == TypeOneofCase.RemoveCharOfID) hash ^= RemoveCharOfID.GetHashCode();
    if (typeCase_ == TypeOneofCase.Name) hash ^= Name.GetHashCode();
    hash ^= (int) typeCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (typeCase_ == TypeOneofCase.Input) {
      output.WriteRawTag(10);
      output.WriteMessage(Input);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerRequest) {
      output.WriteRawTag(18);
      output.WriteString(NewPlayerRequest);
    }
    if (typeCase_ == TypeOneofCase.UpdateCharData) {
      output.WriteRawTag(26);
      output.WriteMessage(UpdateCharData);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerGrant) {
      output.WriteRawTag(34);
      output.WriteMessage(NewPlayerGrant);
    }
    if (typeCase_ == TypeOneofCase.NewRemoteChar) {
      output.WriteRawTag(42);
      output.WriteMessage(NewRemoteChar);
    }
    if (typeCase_ == TypeOneofCase.RemoveCharOfID) {
      output.WriteRawTag(48);
      output.WriteInt32(RemoveCharOfID);
    }
    if (typeCase_ == TypeOneofCase.Name) {
      output.WriteRawTag(58);
      output.WriteString(Name);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (typeCase_ == TypeOneofCase.Input) {
      output.WriteRawTag(10);
      output.WriteMessage(Input);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerRequest) {
      output.WriteRawTag(18);
      output.WriteString(NewPlayerRequest);
    }
    if (typeCase_ == TypeOneofCase.UpdateCharData) {
      output.WriteRawTag(26);
      output.WriteMessage(UpdateCharData);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerGrant) {
      output.WriteRawTag(34);
      output.WriteMessage(NewPlayerGrant);
    }
    if (typeCase_ == TypeOneofCase.NewRemoteChar) {
      output.WriteRawTag(42);
      output.WriteMessage(NewRemoteChar);
    }
    if (typeCase_ == TypeOneofCase.RemoveCharOfID) {
      output.WriteRawTag(48);
      output.WriteInt32(RemoveCharOfID);
    }
    if (typeCase_ == TypeOneofCase.Name) {
      output.WriteRawTag(58);
      output.WriteString(Name);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (typeCase_ == TypeOneofCase.Input) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Input);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerRequest) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NewPlayerRequest);
    }
    if (typeCase_ == TypeOneofCase.UpdateCharData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateCharData);
    }
    if (typeCase_ == TypeOneofCase.NewPlayerGrant) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(NewPlayerGrant);
    }
    if (typeCase_ == TypeOneofCase.NewRemoteChar) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(NewRemoteChar);
    }
    if (typeCase_ == TypeOneofCase.RemoveCharOfID) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RemoveCharOfID);
    }
    if (typeCase_ == TypeOneofCase.Name) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BaseMessage other) {
    if (other == null) {
      return;
    }
    switch (other.TypeCase) {
      case TypeOneofCase.Input:
        if (Input == null) {
          Input = new global::PlayerInput();
        }
        Input.MergeFrom(other.Input);
        break;
      case TypeOneofCase.NewPlayerRequest:
        NewPlayerRequest = other.NewPlayerRequest;
        break;
      case TypeOneofCase.UpdateCharData:
        if (UpdateCharData == null) {
          UpdateCharData = new global::CharacterData();
        }
        UpdateCharData.MergeFrom(other.UpdateCharData);
        break;
      case TypeOneofCase.NewPlayerGrant:
        if (NewPlayerGrant == null) {
          NewPlayerGrant = new global::CharacterData();
        }
        NewPlayerGrant.MergeFrom(other.NewPlayerGrant);
        break;
      case TypeOneofCase.NewRemoteChar:
        if (NewRemoteChar == null) {
          NewRemoteChar = new global::CharacterData();
        }
        NewRemoteChar.MergeFrom(other.NewRemoteChar);
        break;
      case TypeOneofCase.RemoveCharOfID:
        RemoveCharOfID = other.RemoveCharOfID;
        break;
      case TypeOneofCase.Name:
        Name = other.Name;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::PlayerInput subBuilder = new global::PlayerInput();
          if (typeCase_ == TypeOneofCase.Input) {
            subBuilder.MergeFrom(Input);
          }
          input.ReadMessage(subBuilder);
          Input = subBuilder;
          break;
        }
        case 18: {
          NewPlayerRequest = input.ReadString();
          break;
        }
        case 26: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.UpdateCharData) {
            subBuilder.MergeFrom(UpdateCharData);
          }
          input.ReadMessage(subBuilder);
          UpdateCharData = subBuilder;
          break;
        }
        case 34: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.NewPlayerGrant) {
            subBuilder.MergeFrom(NewPlayerGrant);
          }
          input.ReadMessage(subBuilder);
          NewPlayerGrant = subBuilder;
          break;
        }
        case 42: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.NewRemoteChar) {
            subBuilder.MergeFrom(NewRemoteChar);
          }
          input.ReadMessage(subBuilder);
          NewRemoteChar = subBuilder;
          break;
        }
        case 48: {
          RemoveCharOfID = input.ReadInt32();
          break;
        }
        case 58: {
          Name = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::PlayerInput subBuilder = new global::PlayerInput();
          if (typeCase_ == TypeOneofCase.Input) {
            subBuilder.MergeFrom(Input);
          }
          input.ReadMessage(subBuilder);
          Input = subBuilder;
          break;
        }
        case 18: {
          NewPlayerRequest = input.ReadString();
          break;
        }
        case 26: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.UpdateCharData) {
            subBuilder.MergeFrom(UpdateCharData);
          }
          input.ReadMessage(subBuilder);
          UpdateCharData = subBuilder;
          break;
        }
        case 34: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.NewPlayerGrant) {
            subBuilder.MergeFrom(NewPlayerGrant);
          }
          input.ReadMessage(subBuilder);
          NewPlayerGrant = subBuilder;
          break;
        }
        case 42: {
          global::CharacterData subBuilder = new global::CharacterData();
          if (typeCase_ == TypeOneofCase.NewRemoteChar) {
            subBuilder.MergeFrom(NewRemoteChar);
          }
          input.ReadMessage(subBuilder);
          NewRemoteChar = subBuilder;
          break;
        }
        case 48: {
          RemoveCharOfID = input.ReadInt32();
          break;
        }
        case 58: {
          Name = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Vector2Data : pb::IMessage<Vector2Data>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Vector2Data> _parser = new pb::MessageParser<Vector2Data>(() => new Vector2Data());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Vector2Data> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataTypesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Vector2Data() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Vector2Data(Vector2Data other) : this() {
    x_ = other.x_;
    y_ = other.y_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Vector2Data Clone() {
    return new Vector2Data(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private float x_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float X {
    get { return x_; }
    set {
      x_ = value;
    }
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private float y_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Y {
    get { return y_; }
    set {
      y_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Vector2Data);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Vector2Data other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
    if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (X != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(X);
    }
    if (Y != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Y);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (X != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(X);
    }
    if (Y != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Y);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (X != 0F) {
      size += 1 + 4;
    }
    if (Y != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Vector2Data other) {
    if (other == null) {
      return;
    }
    if (other.X != 0F) {
      X = other.X;
    }
    if (other.Y != 0F) {
      Y = other.Y;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          X = input.ReadFloat();
          break;
        }
        case 21: {
          Y = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 13: {
          X = input.ReadFloat();
          break;
        }
        case 21: {
          Y = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class PlayerInput : pb::IMessage<PlayerInput>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlayerInput> _parser = new pb::MessageParser<PlayerInput>(() => new PlayerInput());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayerInput> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataTypesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerInput() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerInput(PlayerInput other) : this() {
    pos_ = other.pos_ != null ? other.pos_.Clone() : null;
    lookPos_ = other.lookPos_ != null ? other.lookPos_.Clone() : null;
    switch (other.ItemCase) {
      case ItemOneofCase.PickupItem:
        PickupItem = other.PickupItem;
        break;
      case ItemOneofCase.ItemAction:
        ItemAction = other.ItemAction;
        break;
      case ItemOneofCase.ItemActionPos:
        ItemActionPos = other.ItemActionPos;
        break;
      case ItemOneofCase.DropItem:
        DropItem = other.DropItem;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerInput Clone() {
    return new PlayerInput(this);
  }

  /// <summary>Field number for the "pos" field.</summary>
  public const int PosFieldNumber = 1;
  private global::Vector2Data pos_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Vector2Data Pos {
    get { return pos_; }
    set {
      pos_ = value;
    }
  }

  /// <summary>Field number for the "lookPos" field.</summary>
  public const int LookPosFieldNumber = 2;
  private global::Vector2Data lookPos_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Vector2Data LookPos {
    get { return lookPos_; }
    set {
      lookPos_ = value;
    }
  }

  /// <summary>Field number for the "PickupItem" field.</summary>
  public const int PickupItemFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PickupItem {
    get { return itemCase_ == ItemOneofCase.PickupItem ? (int) item_ : 0; }
    set {
      item_ = value;
      itemCase_ = ItemOneofCase.PickupItem;
    }
  }

  /// <summary>Field number for the "ItemAction" field.</summary>
  public const int ItemActionFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ItemAction {
    get { return itemCase_ == ItemOneofCase.ItemAction ? (int) item_ : 0; }
    set {
      item_ = value;
      itemCase_ = ItemOneofCase.ItemAction;
    }
  }

  /// <summary>Field number for the "ItemActionPos" field.</summary>
  public const int ItemActionPosFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool ItemActionPos {
    get { return itemCase_ == ItemOneofCase.ItemActionPos ? (bool) item_ : false; }
    set {
      item_ = value;
      itemCase_ = ItemOneofCase.ItemActionPos;
    }
  }

  /// <summary>Field number for the "DropItem" field.</summary>
  public const int DropItemFieldNumber = 6;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool DropItem {
    get { return itemCase_ == ItemOneofCase.DropItem ? (bool) item_ : false; }
    set {
      item_ = value;
      itemCase_ = ItemOneofCase.DropItem;
    }
  }

  private object item_;
  /// <summary>Enum of possible cases for the "Item" oneof.</summary>
  public enum ItemOneofCase {
    None = 0,
    PickupItem = 3,
    ItemAction = 4,
    ItemActionPos = 5,
    DropItem = 6,
  }
  private ItemOneofCase itemCase_ = ItemOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ItemOneofCase ItemCase {
    get { return itemCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearItem() {
    itemCase_ = ItemOneofCase.None;
    item_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayerInput);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayerInput other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Pos, other.Pos)) return false;
    if (!object.Equals(LookPos, other.LookPos)) return false;
    if (PickupItem != other.PickupItem) return false;
    if (ItemAction != other.ItemAction) return false;
    if (ItemActionPos != other.ItemActionPos) return false;
    if (DropItem != other.DropItem) return false;
    if (ItemCase != other.ItemCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (pos_ != null) hash ^= Pos.GetHashCode();
    if (lookPos_ != null) hash ^= LookPos.GetHashCode();
    if (itemCase_ == ItemOneofCase.PickupItem) hash ^= PickupItem.GetHashCode();
    if (itemCase_ == ItemOneofCase.ItemAction) hash ^= ItemAction.GetHashCode();
    if (itemCase_ == ItemOneofCase.ItemActionPos) hash ^= ItemActionPos.GetHashCode();
    if (itemCase_ == ItemOneofCase.DropItem) hash ^= DropItem.GetHashCode();
    hash ^= (int) itemCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (pos_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Pos);
    }
    if (lookPos_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(LookPos);
    }
    if (itemCase_ == ItemOneofCase.PickupItem) {
      output.WriteRawTag(24);
      output.WriteInt32(PickupItem);
    }
    if (itemCase_ == ItemOneofCase.ItemAction) {
      output.WriteRawTag(32);
      output.WriteInt32(ItemAction);
    }
    if (itemCase_ == ItemOneofCase.ItemActionPos) {
      output.WriteRawTag(40);
      output.WriteBool(ItemActionPos);
    }
    if (itemCase_ == ItemOneofCase.DropItem) {
      output.WriteRawTag(48);
      output.WriteBool(DropItem);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (pos_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Pos);
    }
    if (lookPos_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(LookPos);
    }
    if (itemCase_ == ItemOneofCase.PickupItem) {
      output.WriteRawTag(24);
      output.WriteInt32(PickupItem);
    }
    if (itemCase_ == ItemOneofCase.ItemAction) {
      output.WriteRawTag(32);
      output.WriteInt32(ItemAction);
    }
    if (itemCase_ == ItemOneofCase.ItemActionPos) {
      output.WriteRawTag(40);
      output.WriteBool(ItemActionPos);
    }
    if (itemCase_ == ItemOneofCase.DropItem) {
      output.WriteRawTag(48);
      output.WriteBool(DropItem);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (pos_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
    }
    if (lookPos_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LookPos);
    }
    if (itemCase_ == ItemOneofCase.PickupItem) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PickupItem);
    }
    if (itemCase_ == ItemOneofCase.ItemAction) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemAction);
    }
    if (itemCase_ == ItemOneofCase.ItemActionPos) {
      size += 1 + 1;
    }
    if (itemCase_ == ItemOneofCase.DropItem) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayerInput other) {
    if (other == null) {
      return;
    }
    if (other.pos_ != null) {
      if (pos_ == null) {
        Pos = new global::Vector2Data();
      }
      Pos.MergeFrom(other.Pos);
    }
    if (other.lookPos_ != null) {
      if (lookPos_ == null) {
        LookPos = new global::Vector2Data();
      }
      LookPos.MergeFrom(other.LookPos);
    }
    switch (other.ItemCase) {
      case ItemOneofCase.PickupItem:
        PickupItem = other.PickupItem;
        break;
      case ItemOneofCase.ItemAction:
        ItemAction = other.ItemAction;
        break;
      case ItemOneofCase.ItemActionPos:
        ItemActionPos = other.ItemActionPos;
        break;
      case ItemOneofCase.DropItem:
        DropItem = other.DropItem;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (pos_ == null) {
            Pos = new global::Vector2Data();
          }
          input.ReadMessage(Pos);
          break;
        }
        case 18: {
          if (lookPos_ == null) {
            LookPos = new global::Vector2Data();
          }
          input.ReadMessage(LookPos);
          break;
        }
        case 24: {
          PickupItem = input.ReadInt32();
          break;
        }
        case 32: {
          ItemAction = input.ReadInt32();
          break;
        }
        case 40: {
          ItemActionPos = input.ReadBool();
          break;
        }
        case 48: {
          DropItem = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (pos_ == null) {
            Pos = new global::Vector2Data();
          }
          input.ReadMessage(Pos);
          break;
        }
        case 18: {
          if (lookPos_ == null) {
            LookPos = new global::Vector2Data();
          }
          input.ReadMessage(LookPos);
          break;
        }
        case 24: {
          PickupItem = input.ReadInt32();
          break;
        }
        case 32: {
          ItemAction = input.ReadInt32();
          break;
        }
        case 40: {
          ItemActionPos = input.ReadBool();
          break;
        }
        case 48: {
          DropItem = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class CharacterData : pb::IMessage<CharacterData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CharacterData> _parser = new pb::MessageParser<CharacterData>(() => new CharacterData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CharacterData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataTypesReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CharacterData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CharacterData(CharacterData other) : this() {
    characterID_ = other.characterID_;
    pos_ = other.pos_ != null ? other.pos_.Clone() : null;
    name_ = other.name_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CharacterData Clone() {
    return new CharacterData(this);
  }

  /// <summary>Field number for the "characterID" field.</summary>
  public const int CharacterIDFieldNumber = 1;
  private int characterID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CharacterID {
    get { return characterID_; }
    set {
      characterID_ = value;
    }
  }

  /// <summary>Field number for the "pos" field.</summary>
  public const int PosFieldNumber = 2;
  private global::Vector2Data pos_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Vector2Data Pos {
    get { return pos_; }
    set {
      pos_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 3;
  private string name_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_ ?? ""; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasName {
    get { return name_ != null; }
  }
  /// <summary>Clears the value of the "name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearName() {
    name_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CharacterData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CharacterData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CharacterID != other.CharacterID) return false;
    if (!object.Equals(Pos, other.Pos)) return false;
    if (Name != other.Name) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (CharacterID != 0) hash ^= CharacterID.GetHashCode();
    if (pos_ != null) hash ^= Pos.GetHashCode();
    if (HasName) hash ^= Name.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (CharacterID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(CharacterID);
    }
    if (pos_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Pos);
    }
    if (HasName) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (CharacterID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(CharacterID);
    }
    if (pos_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Pos);
    }
    if (HasName) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (CharacterID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CharacterID);
    }
    if (pos_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
    }
    if (HasName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CharacterData other) {
    if (other == null) {
      return;
    }
    if (other.CharacterID != 0) {
      CharacterID = other.CharacterID;
    }
    if (other.pos_ != null) {
      if (pos_ == null) {
        Pos = new global::Vector2Data();
      }
      Pos.MergeFrom(other.Pos);
    }
    if (other.HasName) {
      Name = other.Name;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          CharacterID = input.ReadInt32();
          break;
        }
        case 18: {
          if (pos_ == null) {
            Pos = new global::Vector2Data();
          }
          input.ReadMessage(Pos);
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          CharacterID = input.ReadInt32();
          break;
        }
        case 18: {
          if (pos_ == null) {
            Pos = new global::Vector2Data();
          }
          input.ReadMessage(Pos);
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
